apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__KUBERNETES__NAMESPACE: airflow
  AIRFLOW__CORE__DAGS_FOLDER: /Users/the-greatest/A_Sandbox/Data-Engineering-Projects-2025/Project-1/dags
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin123@airflow-postgres-postgresql:5432/airflow
  AIRFLOW__AUTH_MANAGER__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
